// Static product pages — /products/<slug>/index.html, generated by
// scripts/generate-product-pages.mjs. The slug comes from a data attribute
// baked into the page (no query param, unlike the legacy product.html)
// since each product now has its own real URL.
import { getFlavor, getBundleBySlug } from '../data/products.js';
import { initCartUI, initNav } from './ui.js';
import { resolveProduct, renderPDP } from './lib/pdp.js';

initNav();
const cartUI = initCartUI();

const slug = document.body.dataset.productSlug;
const bundle = getBundleBySlug(slug);
const flavor = bundle ? null : getFlavor(slug);
const product = resolveProduct({ bundle, flavor });

renderPDP(product, { bundle, flavor, cartUI });
